version: '2.1'

services:

  anyblok:
    image: mlfmonde/lab-test-service
    restart: unless-stopped
    depends_on:
      - dbserver
    environment:
      HAPROXY: |
        http-in:
          backends:
            - use_backend_option: "if { base_beg service.qualif.cluster.lab/test1 }"
              port: 8080
              peer_port: 80
      CONSUL_CHECK_URLS: |
        - http://service.qualif.cluster.lab
    volumes:
      - anyblok_data:/var/test_service
      # Simulate a directory that is not a btrfs partition
      - cache_data:/var/cache
    networks:
      - backend
      - cluster_default

  dbserver:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  dbdata:
    driver: anybox/buttervolume:latest
  anyblok_data:
    driver: anybox/buttervolume:latest
    labels:
      - com.github.mlfmonde.cluster.nonmigrable=True
  cache_data:


networks:
  cluster_default:
    external: true
  backend:
